title: Alexander G. Foote
logo: assets/img/profile-pic.png
description: Biomedical Engineering | Precision Genomics | 10+ Years Experience in Translational Research
show_downloads: false
theme: jekyll-theme-minimal
