title: Alexander G. Foote
logo: assets/img/headshot.JPG
description: Biomedical Engineering | Functional Genomics | 10+ Years Experience in Translational Research
show_downloads: false
theme: jekyll-theme-minimal
